### PR TITLE
Upgrade/docs

### PR DESCRIPTION
**Pull request by yannickglt**

### CODE REVIEW

**Comment by firehist** [comment]
Hahaha Good job 👍 
89 files for 1 PR, nice ratio :trollface:

**Comment by yannickglt** [comment]
Ahaa around 80 new icons 😄

**Comment by firehist** [comment]
😍

**Comment by o0baozi0o** [comment]
Really nice jobs !! Could you please also add "react" on that? I am working a lot on that. Thank you~

**Pull request merged**
